export const SELECCIONAR_CLIENTE = "SELECCIONAR_CLIENTE";
export const SELECCIONAR_PRODUCTO = "SELECCIONAR_PRODUCTO";
export const CANTIDAD_PRODUCTOS = "CANTIDAD_PRODUCTOS";
export const ACTUALIZAR_TOTAL = "ACTUALIZAR_TOTAL";
export const LIMPIAR_PEDIDO = "LIMPIAR_PEDIDO";

export const ABRIR_SIDEBAR = "ABRIR_SIDEBAR";
export const CERRAR_SIDEBAR = "CERRAR_SIDEBAR";